#!/usr/bin/env node
/*
 * Builds the deployable server: dist/server.js plus dist/package.json.
 *
 * Shared hosting caps the number of files an account may hold, and a normal
 * `npm install` writes thousands. The bundle folds every pure-JavaScript
 * dependency into one file, so the server only installs the two packages that
 * ship compiled binaries: better-sqlite3 and sharp. Those cannot be bundled,
 * because the binary has to match the server's own Node version and CPU.
 *
 * Output is committed so cPanel can deploy with a git pull and no build step.
 * CI rebuilds and fails if the committed copy is stale.
 */
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const NATIVE = ['better-sqlite3', 'sharp'];

const rootPkg = require(path.join(ROOT, 'package.json'));
const lock = require(path.join(ROOT, 'package-lock.json'));

// Pin the native packages to the exact versions the tests ran against.
const dependencies = {};
for (const name of NATIVE) {
  const entry = lock.packages[`node_modules/${name}`];
  if (!entry) throw new Error(`${name} is missing from package-lock.json — run npm install first.`);
  dependencies[name] = entry.version;
}

fs.mkdirSync(DIST, { recursive: true });

esbuild.buildSync({
  entryPoints: [path.join(ROOT, 'server', 'server.js')],
  outfile: path.join(DIST, 'server.js'),
  bundle: true,
  platform: 'node',
  target: `node${rootPkg.engines.node.replace(/[^0-9.]/g, '').split('.')[0]}`,
  format: 'cjs',
  external: NATIVE,
  define: { __WBS_BUNDLED__: 'true' },
  // Readable stack traces in the cPanel error log matter more than size here.
  minify: false,
  legalComments: 'eof',
  banner: { js: '// GENERATED by scripts/build.js from server/ — do not edit. Run `npm run build`.' },
  logLevel: 'warning',
  logOverride: {
    // express/lib/view.js lazily requires template engines by name; the app
    // uses none, so the unresolved dynamic require is never reached.
    'unsupported-require-call': 'silent',
  },
});

const distPkg = {
  name: `${rootPkg.name}-dist`,
  version: rootPkg.version,
  private: true,
  description: 'Deployable build — generated by scripts/build.js. Install with: npm install --omit=dev',
  main: 'server.js',
  scripts: { start: 'node server.js' },
  engines: rootPkg.engines,
  dependencies,
};
fs.writeFileSync(path.join(DIST, 'package.json'), JSON.stringify(distPkg, null, 2) + '\n');

const size = fs.statSync(path.join(DIST, 'server.js')).size;
console.log(`dist/server.js  ${(size / 1024).toFixed(0)} KB · native deps: ${NATIVE.map(n => `${n}@${dependencies[n]}`).join(', ')}`);
